=== 94Mikel/fp/txurdinaga/TrabajoFicheros/bin/ManejoDeFicheros/ManejodeFicheros.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/ManejodeFicheros/" targetNamespace="http://www.example.org/ManejodeFicheros/">
    


    <element name="Libros">
    	<complexType>
            <choice minOccurs="0" maxOccurs="unbounded">
    			<element name="Libro">
    				<complexType>
    					<sequence>
    						<element name="Autor" type="string"></element>
    						<element name="ISBN" type="string"></element>
    						<element name="Numerodeejemplares" type="string"></element>
    						<element name="Editorial" type="string"></element>
    						<element name="Numerodepaginas" type="string"></element>
    						<element name="AÃ±odeedicion" type="string"></element>
    					</sequence>
    					<attribute name="Titulo" type="string"></attribute>
    				</complexType>
    			</element>
    		</choice>
    	</complexType>
    </element>
</schema>

=== 94Mikel/fp/txurdinaga/java/TrabajoFicheros/ManejodeFicherosMODIFICADO.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:Libros xmlns:ns2="http://www.example.org/ManejodeFicheros/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ManejodeFicheros.xsd">
    <Libro Titulo="La Prueba">
        <Autor>Gari</Autor>
        <ISBN>7854120</ISBN>
        <Numerodeejemplares>200</Numerodeejemplares>
        <Editorial>abc</Editorial>
        <Numerodepaginas>350</Numerodepaginas>
        <Añodeedicion>2016</Añodeedicion>
    </Libro>
    <Libro Titulo="Luces de bohemia">
        <Autor>Camilo Jose Cela</Autor>
        <ISBN>123456789</ISBN>
        <Numerodeejemplares>100</Numerodeejemplares>
        <Editorial>CasaLoca</Editorial>
        <Numerodepaginas>200</Numerodepaginas>
        <Añodeedicion>1984</Añodeedicion>
    </Libro>
    <Libro Titulo="La Factoria">
        <Autor>Camilo Jose Cela</Autor>
        <ISBN>1234</ISBN>
        <Numerodeejemplares>100</Numerodeejemplares>
        <Editorial>CasaLoca</Editorial>
        <Numerodepaginas>200</Numerodepaginas>
        <Añodeedicion>1984</Añodeedicion>
    </Libro>
</ns2:Libros>

=== 94Mikel/fp/txurdinaga/java/TrabajoFicheros/ManejodeFicheros.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Libros xmlns:tns="http://www.example.org/ManejodeFicheros/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ManejodeFicheros/ ManejodeFicheros.xsd ">
  <Libro Titulo="La Prueba">
    <Autor>Gari</Autor>
    <ISBN>7854120</ISBN>
    <Numerodeejemplares>200</Numerodeejemplares>
    <Editorial>abc</Editorial>
    <Numerodepaginas>350</Numerodepaginas>
    <Añodeedicion>2016</Añodeedicion>
  </Libro>
  
</tns:Libros>
