=== 94Mikel/fp/txurdinaga/TrabajoFicheros/bin/AccesoJAXB_ejer/Lugares.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/Lugares/" targetNamespace="http://www.example.org/Lugares/">
    <element name="Lugares">
    	<complexType>
            <choice>
            	<element name="Sitio" minOccurs="0"
            		maxOccurs="unbounded">
            		<complexType>
            			<sequence>
            				<element name="Parking" type="string"></element>
            				<element name="Duchas" type="string"></element>
            				<element name="Hotel" type="string"></element>
            			</sequence>
            			<attribute name="nombre" type="string"></attribute>
            			<attribute name="provincia" type="string"></attribute>
            		</complexType>
            	</element>

            </choice>

    	</complexType>
    </element>
</schema>

=== 94Mikel/fp/txurdinaga/java/TrabajoFicheros/Lugares.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Lugares xmlns:tns="http://www.example.org/Lugares/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Lugares/ src/AccesoJAXB_ejer/Lugares.xsd ">
  <Sitio nombre="la salbaje" provincia="bizkaia">
    <Parking>Si</Parking>
    <Duchas>Si</Duchas>
    <Hotel>No</Hotel>
  </Sitio>
  <Sitio nombre="atxarte" provincia="bizkaia">
    <Parking>Si</Parking>
    <Duchas>No</Duchas>
    <Hotel>No</Hotel>
  </Sitio>
  <Sitio nombre="Pagasarri" provincia="bizkaia">
    <Parking>Si</Parking>
    <Duchas>Si</Duchas>
    <Hotel>No</Hotel>
  </Sitio>
  
</tns:Lugares>
