=== 94Mikel/fp/txurdinaga/TrabajoFicheros/bin/AccesoJAXB/Alumnos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/Alumnos/" targetNamespace="http://www.example.org/Alumnos/">
    <element name="Alumnos">
    	<complexType>
            <choice minOccurs="0" maxOccurs="unbounded">
    			<element name="Alumno">
    				<complexType>
    					<sequence>
    						<element name="Nombre" type="string"></element>
    						<element name="Apellido" type="string"></element>
    						<element name="Grupo" type="string"></element>
    					</sequence>
    					<attribute name="AnoNacimiento" type="string"></attribute>
    				</complexType>
    			</element>
    		</choice>
    	</complexType>
    </element>
</schema>

=== 94Mikel/fp/txurdinaga/TrabajoFicheros/Alumnos2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:Alumnos xmlns:ns2="http://www.example.org/Alumnos/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Alumnos.xsd">
    <Alumno AnoNacimiento="2003">
        <Nombre>dd</Nombre>
        <Apellido>ddddd</Apellido>
        <Grupo>Grudddddpo</Grupo>
    </Alumno>
    <Alumno AnoNacimiento="1975">
        <Nombre>Pepe</Nombre>
        <Apellido>Gotera</Apellido>
        <Grupo>2Âºdw3</Grupo>
    </Alumno>
</ns2:Alumnos>
